# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/athena.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py athena

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }
}

run "plan_enabled" {
  command = plan

  variables {
    name                   = "terratest-plan"
    result_output_location = "s3://terratest-plan-athena-results/output/"

    prepared_statements = {
      events_by_day = {
        query_statement = "SELECT * FROM analytics.events WHERE event_date = ?"
        description     = "Fetch events for a given day"
      }
    }

    capacity_reservation = {
      target_dpus = 24
    }
  }
}

run "plan_disabled" {
  command = plan

  variables {
    name                   = "terratest-plan"
    result_output_location = "s3://terratest-plan-athena-results/output/"

    prepared_statements = {
      events_by_day = {
        query_statement = "SELECT * FROM analytics.events WHERE event_date = ?"
        description     = "Fetch events for a given day"
      }
    }

    capacity_reservation = {
      target_dpus = 24
    }

    enabled = false
  }
}
