# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/mq.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py mq

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }
}

run "plan_enabled" {
  command = plan

  variables {
    name               = "terratest-plan"
    engine_type        = "RabbitMQ"
    engine_version     = "3.13"
    host_instance_type = "mq.t3.micro"
    subnet_ids         = ["subnet-12345678"]
    users = [
      {
        username = "admin"
        password = "TerratestPlan123!"
      }
    ]
    encryption_options = {
      use_aws_owned_key = true
    }
  }
}

run "plan_disabled" {
  command = plan

  variables {
    name               = "terratest-plan"
    engine_type        = "RabbitMQ"
    engine_version     = "3.13"
    host_instance_type = "mq.t3.micro"
    subnet_ids         = ["subnet-12345678"]
    users = [
      {
        username = "admin"
        password = "TerratestPlan123!"
      }
    ]
    encryption_options = {
      use_aws_owned_key = true
    }

    enabled = false
  }
}
