# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/ram.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py ram

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_organizations_organization" {
    defaults = {
      arn = "arn:aws:organizations::123456789012:organization/o-abcdef1234"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }

  mock_resource "aws_ram_resource_share" {
    defaults = {
      id = "arn:aws:ram:us-east-1:123456789012:resource-share/mock"
    }
  }
}

run "plan_enabled" {
  command = plan

  variables {
    name             = "terratest-share"
    ram_resource_arn = "arn:aws:ec2:us-east-1:123456789012:transit-gateway/tgw-12345678"
  }
}

run "plan_disabled" {
  command = plan

  variables {
    name             = "terratest-share"
    ram_resource_arn = "arn:aws:ec2:us-east-1:123456789012:transit-gateway/tgw-12345678"

    enabled = false
  }
}
