# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/organizations.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py organizations

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }

  mock_resource "aws_organizations_organization" {
    defaults = {
      roots = [{ id = "r-mock", arn = "arn:aws:organizations::123456789012:root/o-abcdef1234/r-mock", name = "Root", policy_types = [] }]
    }
  }

  mock_resource "aws_organizations_organizational_unit" {
    defaults = {
      id = "ou-abcd-12345678"
    }
  }
}

run "plan_enabled" {
  command = plan

  variables {
    aws_service_access_principals = ["sso.amazonaws.com"]
    enabled_policy_types          = ["SERVICE_CONTROL_POLICY"]

    organizational_units = {
      security  = { name = "Security" }
      workloads = { name = "Workloads" }
      prod      = { name = "Production", parent_key = "workloads" }
    }

    tags = {
      Environment = "test"
    }
  }
}

run "plan_disabled" {
  command = plan

  variables {
    aws_service_access_principals = ["sso.amazonaws.com"]
    enabled_policy_types          = ["SERVICE_CONTROL_POLICY"]

    organizational_units = {
      security  = { name = "Security" }
      workloads = { name = "Workloads" }
      prod      = { name = "Production", parent_key = "workloads" }
    }

    tags = {
      Environment = "test"
    }

    enabled = false
  }
}
