# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/lake-formation.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py lake-formation

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }
}

run "plan_enabled" {
  command = plan

  variables {
    enabled                   = true
    manage_data_lake_settings = true
    admin_arns                = ["arn:aws:iam::123456789012:role/terratest-lakeformation-admin"]
  }
}

run "plan_disabled" {
  command = plan

  variables {
    manage_data_lake_settings = true
    admin_arns                = ["arn:aws:iam::123456789012:role/terratest-lakeformation-admin"]

    enabled = false
  }
}

# Hand-maintained negative test (preserved verbatim by generate-offline-tests.py).
# Must fail: manage_data_lake_settings with empty admin_arns would remove all
# Lake Formation administrators.
run "invalid_empty_admins" {
  command = plan

  variables {
    enabled                   = true
    manage_data_lake_settings = true
    admin_arns                = []
  }

  expect_failures = [
    var.manage_data_lake_settings,
  ]
}
