# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/cloudmap.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py cloudmap

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }
}

run "plan_enabled" {
  command = plan

  variables {
    name                         = "terratest.local"
    namespace_description        = "Terratest plan namespace"
    create_private_dns_namespace = true
    vpc_id                       = "vpc-12345678"

    services = {
      app = {
        name            = "app"
        description     = "Terratest service"
        dns_ttl         = 10
        dns_record_type = "A"
      }
    }
  }
}

run "plan_disabled" {
  command = plan

  variables {
    name                         = "terratest.local"
    namespace_description        = "Terratest plan namespace"
    create_private_dns_namespace = true
    vpc_id                       = "vpc-12345678"

    services = {
      app = {
        name            = "app"
        description     = "Terratest service"
        dns_ttl         = 10
        dns_record_type = "A"
      }
    }

    enabled = false
  }
}
