# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/vpc__vpc-peering.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py vpc/vpc-peering

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }
}

run "plan_enabled" {
  command = plan

  variables {
    requestor_vpc_id        = "vpc-11111111"
    acceptor_vpc_id         = "vpc-22222222"
    acceptor_aws_account_id = "123456789012"
    acceptor_aws_region     = "us-east-1"
    acceptor_cidr_blocks    = ["10.20.0.0/16"]
  }
}

run "plan_disabled" {
  command = plan

  variables {
    requestor_vpc_id        = "vpc-11111111"
    acceptor_vpc_id         = "vpc-22222222"
    acceptor_aws_account_id = "123456789012"
    acceptor_aws_region     = "us-east-1"
    acceptor_cidr_blocks    = ["10.20.0.0/16"]

    enabled = false
  }
}
