# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/eks__modules__self-managed-node-group.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py eks/modules/self-managed-node-group

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }

  mock_resource "aws_iam_instance_profile" {
    defaults = {
      arn = "arn:aws:iam::123456789012:policy/mock"
    }
  }

  mock_resource "aws_iam_role" {
    defaults = {
      arn = "arn:aws:iam::123456789012:role/mock"
    }
  }

  mock_resource "aws_launch_template" {
    defaults = {
      id = "lt-1234567890abcdef0"
    }
  }
}

run "plan_enabled" {
  command = plan

  variables {
    name                 = "terratest-plan"
    cluster_name         = "terratest"
    cluster_version      = "1.31"
    cluster_service_cidr = "172.20.0.0/16"
    cluster_endpoint     = "https://ABCDEF1234567890.gr7.us-east-1.eks.amazonaws.com"
    cluster_auth_base64  = "dGVzdC1jZXJ0LWRhdGE="
    instance_type        = "t3.medium"
    subnet_ids           = ["subnet-12345678"]
  }
}

run "plan_disabled" {
  command = plan

  variables {
    name                 = "terratest-plan"
    cluster_name         = "terratest"
    cluster_version      = "1.31"
    cluster_service_cidr = "172.20.0.0/16"
    cluster_endpoint     = "https://ABCDEF1234567890.gr7.us-east-1.eks.amazonaws.com"
    cluster_auth_base64  = "dGVzdC1jZXJ0LWRhdGE="
    instance_type        = "t3.medium"
    subnet_ids           = ["subnet-12345678"]

    enabled = false
  }
}
