# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/managed-prefix-list.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py managed-prefix-list

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }
}

run "plan_enabled" {
  command = plan

  variables {
    prefix_lists = {
      corp = {
        name        = "terratest-corp-cidrs"
        max_entries = 10
        cidr_list = [
          { cidr = "10.0.0.0/16", description = "corp network" },
          { cidr = "10.1.0.0/16" },
        ]
      }
    }
  }
}

run "plan_disabled" {
  command = plan

  variables {
    prefix_lists = {
      corp = {
        name        = "terratest-corp-cidrs"
        max_entries = 10
        cidr_list = [
          { cidr = "10.0.0.0/16", description = "corp network" },
          { cidr = "10.1.0.0/16" },
        ]
      }
    }

    enabled = false
  }
}
