# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/fsx.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py fsx

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }

  mock_resource "aws_fsx_ontap_file_system" {
    defaults = {
      id = "fs-0123456789abcdef0"
    }
  }

  mock_resource "aws_fsx_ontap_storage_virtual_machine" {
    defaults = {
      id = "svm-0123456789abcdef0"
    }
  }
}

run "plan_enabled" {
  command = plan

  variables {
    name                  = "terratest-plan"
    file_system_type      = "ONTAP"
    subnet_ids            = ["subnet-12345678"]
    storage_capacity      = 1024
    throughput_capacity   = 128
    ontap_deployment_type = "SINGLE_AZ_1"

    ontap_svms = {
      apps = {
        name = "svm01"
      }
      analytics = {}
    }

    ontap_volumes = {
      data = {
        name              = "data_vol"
        svm_key           = "apps"
        size_in_megabytes = 102400
      }
      logs = {
        name              = "logs_vol"
        svm_key           = "analytics"
        size_in_megabytes = 51200
      }
    }
  }
}

run "plan_disabled" {
  command = plan

  variables {
    name                  = "terratest-plan"
    file_system_type      = "ONTAP"
    subnet_ids            = ["subnet-12345678"]
    storage_capacity      = 1024
    throughput_capacity   = 128
    ontap_deployment_type = "SINGLE_AZ_1"

    ontap_svms = {
      apps = {
        name = "svm01"
      }
      analytics = {}
    }

    ontap_volumes = {
      data = {
        name              = "data_vol"
        svm_key           = "apps"
        size_in_megabytes = 102400
      }
      logs = {
        name              = "logs_vol"
        svm_key           = "analytics"
        size_in_megabytes = 51200
      }
    }

    enabled = false
  }
}
