# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/eks__modules__aws-auth.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py eks/modules/aws-auth

mock_provider "kubernetes" {}

run "plan_enabled" {
  command = plan

  variables {
    manage_aws_auth_configmap = true

    aws_auth_roles = [
      {
        rolearn  = "arn:aws:iam::123456789012:role/terratest-node-role"
        username = "system:node:{{EC2PrivateDNSName}}"
        groups   = ["system:bootstrappers", "system:nodes"]
      },
    ]

    aws_auth_users = [
      {
        userarn  = "arn:aws:iam::123456789012:user/terratest-admin"
        username = "terratest-admin"
        groups   = ["system:masters"]
      },
    ]

    aws_auth_accounts = ["123456789012"]
  }
}

run "plan_disabled" {
  command = plan

  variables {
    manage_aws_auth_configmap = true

    aws_auth_roles = [
      {
        rolearn  = "arn:aws:iam::123456789012:role/terratest-node-role"
        username = "system:node:{{EC2PrivateDNSName}}"
        groups   = ["system:bootstrappers", "system:nodes"]
      },
    ]

    aws_auth_users = [
      {
        userarn  = "arn:aws:iam::123456789012:user/terratest-admin"
        username = "terratest-admin"
        groups   = ["system:masters"]
      },
    ]

    aws_auth_accounts = ["123456789012"]

    enabled = false
  }
}
