# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/api-gateway.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py api-gateway

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }

  mock_resource "aws_api_gateway_stage" {
    defaults = {
      arn = "arn:aws:api:us-east-1:123456789012:mock"
    }
  }

  mock_resource "aws_cloudwatch_log_group" {
    defaults = {
      arn = "arn:aws:logs:us-east-1:123456789012:mock"
    }
  }
}

run "plan_enabled" {
  command = plan

  variables {
    name = "terratest-plan"

    usage_plans = {
      standard = {
        description = "Standard tier"
        quota_settings = {
          limit  = 10000
          period = "MONTH"
        }
        throttle_settings = {
          burst_limit = 100
          rate_limit  = 50
        }
      }
    }

    api_keys = {
      partner = {
        description    = "Partner integration key"
        usage_plan_key = "standard"
      }
    }

    waf_web_acl_arn = "arn:aws:wafv2:eu-west-1:111111111111:regional/webacl/terratest-plan/00000000-0000-0000-0000-000000000000"
  }
}

run "plan_disabled" {
  command = plan

  variables {
    name = "terratest-plan"

    usage_plans = {
      standard = {
        description = "Standard tier"
        quota_settings = {
          limit  = 10000
          period = "MONTH"
        }
        throttle_settings = {
          burst_limit = 100
          rate_limit  = 50
        }
      }
    }

    api_keys = {
      partner = {
        description    = "Partner integration key"
        usage_plan_key = "standard"
      }
    }

    waf_web_acl_arn = "arn:aws:wafv2:eu-west-1:111111111111:regional/webacl/terratest-plan/00000000-0000-0000-0000-000000000000"

    enabled = false
  }
}
