# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/app-runner.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py app-runner

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }

  mock_resource "aws_apprunner_observability_configuration" {
    defaults = {
      arn = "arn:aws:apprunner:us-east-1:123456789012:mock"
    }
  }

  mock_resource "aws_iam_role" {
    defaults = {
      arn = "arn:aws:iam::123456789012:role/mock"
    }
  }
}

run "plan_enabled" {
  command = plan

  variables {
    name = "terratest-plan"
    source_configuration = {
      image_repository = {
        image_identifier      = "public.ecr.aws/nginx/nginx:latest"
        image_repository_type = "ECR_PUBLIC"
        image_configuration   = { port = "80" }
      }
    }
  }
}

run "plan_disabled" {
  command = plan

  variables {
    name = "terratest-plan"
    source_configuration = {
      image_repository = {
        image_identifier      = "public.ecr.aws/nginx/nginx:latest"
        image_repository_type = "ECR_PUBLIC"
        image_configuration   = { port = "80" }
      }
    }

    enabled = false
  }
}
