# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/kinesis-firehose.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py kinesis-firehose

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }

  mock_resource "aws_iam_policy" {
    defaults = {
      arn = "arn:aws:iam::123456789012:policy/mock"
    }
  }

  mock_resource "aws_iam_role" {
    defaults = {
      arn = "arn:aws:iam::123456789012:role/mock"
    }
  }
}

run "plan_enabled" {
  command = plan

  variables {
    name                                  = "terratest-plan"
    destination                           = "extended_s3"
    s3_bucket_arn                         = "arn:aws:s3:::terratest-firehose-dest"
    firehose_role                         = "arn:aws:iam::123456789012:role/terratest-firehose"
    vpc_create_destination_security_group = false
  }
}

run "plan_disabled" {
  command = plan

  variables {
    name                                  = "terratest-plan"
    destination                           = "extended_s3"
    s3_bucket_arn                         = "arn:aws:s3:::terratest-firehose-dest"
    firehose_role                         = "arn:aws:iam::123456789012:role/terratest-firehose"
    vpc_create_destination_security_group = false

    enabled = false
  }
}

# Hand-maintained negative test (preserved verbatim by generate-offline-tests.py).
# Must fail: create_role = true with both name and role_name null leaves the
# IAM role without a valid name.
run "invalid_role_no_name" {
  command = plan

  variables {
    destination                           = "extended_s3"
    s3_bucket_arn                         = "arn:aws:s3:::terratest-firehose-dest"
    vpc_create_destination_security_group = false

    create_role = true
    # name and role_name intentionally omitted (both default to null)

    # The destination-log path interpolates local.name into the CloudWatch
    # log group name and hard-errors on null before expect_failures can be
    # checked - switch it off so only the create_role validation fires.
    enable_destination_log          = false
    create_destination_cw_log_group = false
  }

  expect_failures = [
    var.create_role,
  ]
}
