# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/elasticache.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py elasticache

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }
}

mock_provider "random" {}

run "plan_enabled" {
  command = plan

  variables {
    create_cluster           = false
    create_replication_group = true

    name        = "terratest-plan"
    description = "Terratest plan replication group"

    engine         = "redis"
    engine_version = "7.1"
    node_type      = "cache.t4g.micro"

    cluster_mode_enabled = false
    num_cache_clusters   = 2

    transit_encryption_enabled = true
    at_rest_encryption_enabled = true

    create_parameter_group = false
    create_subnet_group    = false
    create_security_group  = false
  }
}

run "plan_disabled" {
  command = plan

  variables {
    create_cluster           = false
    create_replication_group = true

    name        = "terratest-plan"
    description = "Terratest plan replication group"

    engine         = "redis"
    engine_version = "7.1"
    node_type      = "cache.t4g.micro"

    cluster_mode_enabled = false
    num_cache_clusters   = 2

    transit_encryption_enabled = true
    at_rest_encryption_enabled = true

    create_parameter_group = false
    create_subnet_group    = false
    create_security_group  = false

    enabled = false
  }
}
