# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/eks__modules___user_data.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py eks/modules/_user_data

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }
}

mock_provider "null" {}

mock_provider "cloudinit" {}

run "plan_enabled" {
  command = plan

  variables {
    platform                   = "linux"
    cluster_name               = "terratest"
    cluster_endpoint           = "https://ABCDEF1234567890.gr7.us-east-1.eks.amazonaws.com"
    cluster_auth_base64        = "dGVzdC1jZXJ0LWRhdGE="
    cluster_service_cidr       = "172.20.0.0/16"
    enable_bootstrap_user_data = true
  }
}

run "plan_disabled" {
  command = plan

  variables {
    platform                   = "linux"
    cluster_name               = "terratest"
    cluster_endpoint           = "https://ABCDEF1234567890.gr7.us-east-1.eks.amazonaws.com"
    cluster_auth_base64        = "dGVzdC1jZXJ0LWRhdGE="
    cluster_service_cidr       = "172.20.0.0/16"
    enable_bootstrap_user_data = true

    enabled = false
  }
}
