# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/iam-identity-center.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py iam-identity-center

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }

  mock_data "aws_ssoadmin_instances" {
    defaults = {
      arns               = ["arn:aws:sso:::instance/ssoins-1234567890abcdef"]
      identity_store_ids = ["d-1234567890"]
    }
  }
}

run "plan_enabled" {
  command = plan

  variables {
    sso_groups = {
      platform = {
        group_name        = "terratest-platform"
        group_description = "Terratest plan fixture group"
      }
    }
    sso_users = {}
  }
}

run "plan_disabled" {
  command = plan

  variables {
    sso_groups = {
      platform = {
        group_name        = "terratest-platform"
        group_description = "Terratest plan fixture group"
      }
    }
    sso_users = {}

    enabled = false
  }
}
