# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/codebuild-runners.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py codebuild-runners

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_iam_role" {
    defaults = {
      arn = "arn:aws:iam::123456789012:role/mock"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }

  mock_resource "aws_iam_role" {
    defaults = {
      arn = "arn:aws:iam::123456789012:role/mock"
    }
  }
}

run "plan_enabled" {
  command = plan

  variables {
    env_name                 = "terratest"
    repository_name          = "test-repo"
    github_organization_name = "test-org"
    vpc_id                   = "vpc-0123456789abcdef0"
    codebuild_subnets        = ["subnet-12345678", "subnet-87654321"]

    create_iam_role      = true
    codebuild_iam_policy = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":[\"logs:CreateLogStream\",\"logs:PutLogEvents\"],\"Resource\":\"*\"}]}"

    create_security_group = true

    codebuild_runner_repository_url = "123456789012.dkr.ecr.us-east-1.amazonaws.com/codebuild-runner"
  }
}

run "plan_disabled" {
  command = plan

  variables {
    env_name                 = "terratest"
    repository_name          = "test-repo"
    github_organization_name = "test-org"
    vpc_id                   = "vpc-0123456789abcdef0"
    codebuild_subnets        = ["subnet-12345678", "subnet-87654321"]

    create_iam_role      = true
    codebuild_iam_policy = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":[\"logs:CreateLogStream\",\"logs:PutLogEvents\"],\"Resource\":\"*\"}]}"

    create_security_group = true

    codebuild_runner_repository_url = "123456789012.dkr.ecr.us-east-1.amazonaws.com/codebuild-runner"

    enabled = false
  }
}
