# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/amp.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py amp

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }

  mock_resource "aws_cloudwatch_log_group" {
    defaults = {
      arn = "arn:aws:logs:us-east-1:123456789012:mock"
    }
  }
}

run "plan_enabled" {
  command = plan

  variables {
    name = "terratest-plan"

    create_cloudwatch_log_group = true

    create_alert_manager_definition = true

    alert_manager_definition = <<-EOT
      alertmanager_config: |
        route:
          receiver: 'default'
        receivers:
          - name: 'default'
    EOT

    rule_group_namespaces = {
      default = {
        name = "terratest-rules"
        data = <<-EOT
          groups:
            - name: test
              rules:
                - record: metric:recording_rule
                  expr: avg(rate(container_cpu_usage_seconds_total[5m]))
        EOT
      }
    }
  }
}

run "plan_disabled" {
  command = plan

  variables {
    name = "terratest-plan"

    create_cloudwatch_log_group = true

    create_alert_manager_definition = true

    alert_manager_definition = <<-EOT
      alertmanager_config: |
        route:
          receiver: 'default'
        receivers:
          - name: 'default'
    EOT

    rule_group_namespaces = {
      default = {
        name = "terratest-rules"
        data = <<-EOT
          groups:
            - name: test
              rules:
                - record: metric:recording_rule
                  expr: avg(rate(container_cpu_usage_seconds_total[5m]))
        EOT
      }
    }

    enabled = false
  }
}
