# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/chatbot-slack.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py chatbot-slack

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }
}

run "plan_enabled" {
  command = plan

  variables {
    name                             = "terratest-plan"
    slack_channel_configuration_name = "terratest-plan"
    slack_channel_id                 = "C0TEST1234"
    slack_workspace_id               = "T0TEST1234"
    sns_topic_arns                   = []
    logging_level                    = "ERROR"
  }
}

run "plan_disabled" {
  command = plan

  variables {
    name                             = "terratest-plan"
    slack_channel_configuration_name = "terratest-plan"
    slack_channel_id                 = "C0TEST1234"
    slack_workspace_id               = "T0TEST1234"
    sns_topic_arns                   = []
    logging_level                    = "ERROR"

    enabled = false
  }
}
