# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/msk.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py msk

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }
}

run "plan_enabled" {
  command = plan

  variables {
    name                   = "terratest-plan"
    kafka_version          = "3.6.0"
    number_of_broker_nodes = 2
    broker_instance_type   = "kafka.t3.small"
    broker_subnets         = ["subnet-12345678", "subnet-87654321"]

    cluster_policy = <<-EOT
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "AllowConsumerAccount",
            "Effect": "Allow",
            "Principal": {
              "AWS": "arn:aws:iam::123456789012:root"
            },
            "Action": [
              "kafka:GetBootstrapBrokers",
              "kafka:DescribeCluster",
              "kafka:DescribeClusterV2"
            ],
            "Resource": "*"
          }
        ]
      }
    EOT
  }
}

run "plan_disabled" {
  command = plan

  variables {
    name                   = "terratest-plan"
    kafka_version          = "3.6.0"
    number_of_broker_nodes = 2
    broker_instance_type   = "kafka.t3.small"
    broker_subnets         = ["subnet-12345678", "subnet-87654321"]

    cluster_policy = <<-EOT
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "AllowConsumerAccount",
            "Effect": "Allow",
            "Principal": {
              "AWS": "arn:aws:iam::123456789012:root"
            },
            "Action": [
              "kafka:GetBootstrapBrokers",
              "kafka:DescribeCluster",
              "kafka:DescribeClusterV2"
            ],
            "Resource": "*"
          }
        ]
      }
    EOT

    enabled = false
  }
}

# Hand-maintained negative test (preserved verbatim by generate-offline-tests.py).
# Must fail: provisioned MSK cluster requires broker_subnets with >= 2 subnet IDs.
run "invalid_single_subnet" {
  command = plan

  variables {
    name                   = "terratest-plan"
    kafka_version          = "3.6.0"
    number_of_broker_nodes = 2
    broker_instance_type   = "kafka.t3.small"
    broker_subnets         = ["subnet-12345678"]
  }

  expect_failures = [
    var.broker_subnets,
  ]
}
