# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/redshift.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py redshift

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }
}

mock_provider "random" {}

run "plan_enabled" {
  command = plan

  variables {
    cluster_identifier = "terratest-plan"
    node_type          = "dc2.large"
    master_username    = "admin"
    logging = {
      log_destination_type = "cloudwatch"
      log_exports          = ["connectionlog"]
    }
    port = 5439
  }
}

run "plan_disabled" {
  command = plan

  variables {
    cluster_identifier = "terratest-plan"
    node_type          = "dc2.large"
    master_username    = "admin"
    logging = {
      log_destination_type = "cloudwatch"
      log_exports          = ["connectionlog"]
    }
    port = 5439

    enabled = false
  }
}
