# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/bastion.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py bastion

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }

  mock_resource "aws_launch_template" {
    defaults = {
      id = "lt-1234567890abcdef0"
    }
  }
}

mock_provider "cloudinit" {}

mock_provider "tls" {}

run "plan_enabled" {
  command = plan

  variables {
    enabled                = true
    name                   = "test-bastion"
    subnet_id              = "subnet-0123456789abcdef0"
    vpc_security_group_ids = ["sg-0123456789abcdef0"]
    instance_type          = "t4g.nano"
    public                 = true

    allowed_ssh_cidrs = ["203.0.113.0/24"]

    tunnel_users = {
      dev_user = {
        ssh_public_key  = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKLxJMPJXtLZYz7IljYqIvjcUBbCGRHyhZGJ3UwF1DYM test@example.com"
        allowed_tunnels = ["db.internal:5432", "redis.internal:6379"]
      }
    }

    session_log_retention_days   = 7
    session_idle_timeout_minutes = 20
  }
}

run "plan_disabled" {
  command = plan

  variables {
    name                   = "test-bastion"
    subnet_id              = "subnet-0123456789abcdef0"
    vpc_security_group_ids = ["sg-0123456789abcdef0"]
    instance_type          = "t4g.nano"
    public                 = true

    allowed_ssh_cidrs = ["203.0.113.0/24"]

    tunnel_users = {
      dev_user = {
        ssh_public_key  = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKLxJMPJXtLZYz7IljYqIvjcUBbCGRHyhZGJ3UwF1DYM test@example.com"
        allowed_tunnels = ["db.internal:5432", "redis.internal:6379"]
      }
    }

    session_log_retention_days   = 7
    session_idle_timeout_minutes = 20

    enabled = false
  }
}
