# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/headscale__subnet-router.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py headscale/subnet-router

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }

  mock_resource "aws_iam_policy" {
    defaults = {
      arn = "arn:aws:iam::123456789012:policy/mock"
    }
  }

  mock_resource "aws_launch_template" {
    defaults = {
      id = "lt-1234567890abcdef0"
    }
  }

  mock_resource "aws_sns_topic" {
    defaults = {
      arn = "arn:aws:sns:us-east-1:123456789012:mock"
    }
  }
}

mock_provider "cloudinit" {}

run "plan_enabled" {
  command = plan

  variables {
    name                 = "terratest-plan"
    vpc_id               = "vpc-12345678"
    subnet_id            = "subnet-12345678"
    headscale_server_url = "https://hs.example.com"
    headscale_auth_key   = "hskey-test123"
    advertise_routes     = ["10.0.0.0/16"]
    secrets_manager_arn  = "arn:aws:secretsmanager:us-east-1:123456789012:secret:test"
    ami_id               = "ami-12345678"
  }
}

run "plan_disabled" {
  command = plan

  variables {
    name                 = "terratest-plan"
    vpc_id               = "vpc-12345678"
    subnet_id            = "subnet-12345678"
    headscale_server_url = "https://hs.example.com"
    headscale_auth_key   = "hskey-test123"
    advertise_routes     = ["10.0.0.0/16"]
    secrets_manager_arn  = "arn:aws:secretsmanager:us-east-1:123456789012:secret:test"
    ami_id               = "ami-12345678"

    enabled = false
  }
}
