# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/redshift-serverless.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py redshift-serverless

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }

  mock_resource "aws_iam_role" {
    defaults = {
      arn = "arn:aws:iam::123456789012:role/mock"
    }
  }
}

mock_provider "random" {}

mock_provider "time" {}

run "plan_enabled" {
  command = plan

  variables {
    name           = "terratest-plan"
    enabled        = true
    admin_username = "admin"
    namespace_name = "terratest"
    workgroup_name = "terratest-workgroup"
    subnet_ids     = ["subnet-12345678", "subnet-23456789", "subnet-34567890"]
    vpc_id         = "vpc-12345678"
    iam_role_name  = "terratest-redshift-role"

    # keep the plan fixture minimal - namespace + workgroup only
    endpoint_enabled = false
  }
}

run "plan_disabled" {
  command = plan

  variables {
    name           = "terratest-plan"
    admin_username = "admin"
    namespace_name = "terratest"
    workgroup_name = "terratest-workgroup"
    subnet_ids     = ["subnet-12345678", "subnet-23456789", "subnet-34567890"]
    vpc_id         = "vpc-12345678"
    iam_role_name  = "terratest-redshift-role"

    # keep the plan fixture minimal - namespace + workgroup only
    endpoint_enabled = false

    enabled = false
  }
}
