# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/eks__modules__hybrid-node-role.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py eks/modules/hybrid-node-role

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }

  mock_resource "aws_iam_policy" {
    defaults = {
      arn = "arn:aws:iam::123456789012:policy/mock"
    }
  }
}

run "plan_enabled" {
  command = plan

  variables {
    name         = "terratest-plan"
    cluster_arns = ["arn:aws:eks:us-east-1:123456789012:cluster/test"]
  }
}

run "plan_disabled" {
  command = plan

  variables {
    name         = "terratest-plan"
    cluster_arns = ["arn:aws:eks:us-east-1:123456789012:cluster/test"]

    enabled = false
  }
}
