# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/route53__resolver-rule-associations.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py route53/resolver-rule-associations

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }
}

run "plan_enabled" {
  command = plan

  variables {
    vpc_id = "vpc-12345678"

    resolver_rules = {
      onprem = {
        domain_name          = "corp.example.com"
        rule_type            = "FORWARD"
        resolver_endpoint_id = "rslvr-out-0123456789abcdef0"
        target_ips = [
          { ip = "10.10.0.10" },
          { ip = "10.10.1.10" },
        ]
      }
    }

    resolver_rule_associations = {
      onprem = {}
    }
  }
}

run "plan_disabled" {
  command = plan

  variables {
    vpc_id = "vpc-12345678"

    resolver_rules = {
      onprem = {
        domain_name          = "corp.example.com"
        rule_type            = "FORWARD"
        resolver_endpoint_id = "rslvr-out-0123456789abcdef0"
        target_ips = [
          { ip = "10.10.0.10" },
          { ip = "10.10.1.10" },
        ]
      }
    }

    resolver_rule_associations = {
      onprem = {}
    }

    enabled = false
  }
}
