# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/lambda__modules__deploy.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py lambda/modules/deploy

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_iam_role" {
    defaults = {
      arn = "arn:aws:iam::123456789012:role/mock"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }

  mock_resource "aws_iam_role" {
    defaults = {
      arn = "arn:aws:iam::123456789012:role/mock"
    }
  }
}

mock_provider "null" {}

run "plan_enabled" {
  command = plan

  variables {
    alias_name            = "terratest"
    function_name         = "terratest-function"
    target_version        = "1"
    current_version       = "1"
    app_name              = "terratest-deploy"
    deployment_group_name = "terratest-deploy-group"

    # Exercise the CodeDeploy app + deployment group + IAM role paths so the
    # plan creates real resources (plan-only; nothing is applied in CI).
    enabled                 = true
    create_app              = true
    create_deployment_group = true
    create_codedeploy_role  = true
    create_deployment       = false
  }
}

run "plan_disabled" {
  command = plan

  variables {
    alias_name            = "terratest"
    function_name         = "terratest-function"
    target_version        = "1"
    current_version       = "1"
    app_name              = "terratest-deploy"
    deployment_group_name = "terratest-deploy-group"

    # Exercise the CodeDeploy app + deployment group + IAM role paths so the
    # plan creates real resources (plan-only; nothing is applied in CI).
    create_app              = true
    create_deployment_group = true
    create_codedeploy_role  = true
    create_deployment       = false

    enabled = false
  }
}
