# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/ssm-document.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py ssm-document

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }
}

run "plan_enabled" {
  command = plan

  variables {
    name            = "terratest-plan-doc"
    document_type   = "Command"
    document_format = "JSON"

    content = <<-EOT
    {
      "schemaVersion": "2.2",
      "description": "terratest plan fixture",
      "mainSteps": [
        {
          "action": "aws:runShellScript",
          "name": "example",
          "inputs": { "runCommand": ["echo hello"] }
        }
      ]
    }
    EOT
  }
}

run "plan_disabled" {
  command = plan

  variables {
    name            = "terratest-plan-doc"
    document_type   = "Command"
    document_format = "JSON"

    content = <<-EOT
    {
      "schemaVersion": "2.2",
      "description": "terratest plan fixture",
      "mainSteps": [
        {
          "action": "aws:runShellScript",
          "name": "example",
          "inputs": { "runCommand": ["echo hello"] }
        }
      ]
    }
    EOT

    enabled = false
  }
}

run "invalid_name_charset" {
  command = plan

  variables {
    name    = "ab"
    content = "{}"
  }

  expect_failures = [var.name]
}

run "invalid_name_reserved_prefix" {
  command = plan

  variables {
    name    = "aws-my-doc"
    content = "{}"
  }

  expect_failures = [var.name]
}

run "invalid_content_empty" {
  command = plan

  variables {
    name    = "valid-doc-name"
    content = "   "
  }

  expect_failures = [var.content]
}

run "invalid_document_type" {
  command = plan

  variables {
    name          = "valid-doc-name"
    content       = "{}"
    document_type = "Bogus"
  }

  expect_failures = [var.document_type]
}

run "invalid_document_format" {
  command = plan

  variables {
    name            = "valid-doc-name"
    content         = "{}"
    document_format = "XML"
  }

  expect_failures = [var.document_format]
}
