# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/appconfig.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py appconfig

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }

  mock_resource "aws_appconfig_application" {
    defaults = {
      id = "a1b2c3d"
    }
  }

  mock_resource "aws_appconfig_configuration_profile" {
    defaults = {
      configuration_profile_id = "c1d2e3f"
    }
  }

  mock_resource "aws_appconfig_environment" {
    defaults = {
      environment_id = "e1f2g3d"
    }
  }
}

run "plan_enabled" {
  command = plan

  variables {
    name = "terratest-plan"

    environments = {
      production = {
        description = "Terratest production environment"
      }
    }

    configuration_profiles = {
      app-settings = {
        description = "Terratest application settings"
      }
    }

    hosted_configuration_versions = {
      app-settings = {
        content = "{\"feature_enabled\":true}"
      }
    }

    deployment_strategies = {
      fast = {
        deployment_duration_in_minutes = 5
        growth_factor                  = 25
      }
    }
  }
}

run "plan_disabled" {
  command = plan

  variables {
    name = "terratest-plan"

    environments = {
      production = {
        description = "Terratest production environment"
      }
    }

    configuration_profiles = {
      app-settings = {
        description = "Terratest application settings"
      }
    }

    hosted_configuration_versions = {
      app-settings = {
        content = "{\"feature_enabled\":true}"
      }
    }

    deployment_strategies = {
      fast = {
        deployment_duration_in_minutes = 5
        growth_factor                  = 25
      }
    }

    enabled = false
  }
}
