# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/dms.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py dms

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }
}

mock_provider "time" {}

run "plan_enabled" {
  command = plan

  variables {
    create_repl_instance     = false
    create_repl_subnet_group = false
    create_iam_roles         = false
    create_access_iam_role   = false

    endpoints = {
      source = {
        endpoint_id                     = "terratest-source"
        endpoint_type                   = "source"
        engine_name                     = "aurora-postgresql"
        database_name                   = "appdb"
        secrets_manager_arn             = "arn:aws:secretsmanager:us-east-1:123456789012:secret:dms-source-AbCdEf"
        secrets_manager_access_role_arn = "arn:aws:iam::123456789012:role/dms-secrets-access"
        ssl_mode                        = "require"
      }
    }
  }
}

run "plan_disabled" {
  command = plan

  variables {
    create_repl_instance     = false
    create_repl_subnet_group = false
    create_iam_roles         = false
    create_access_iam_role   = false

    endpoints = {
      source = {
        endpoint_id                     = "terratest-source"
        endpoint_type                   = "source"
        engine_name                     = "aurora-postgresql"
        database_name                   = "appdb"
        secrets_manager_arn             = "arn:aws:secretsmanager:us-east-1:123456789012:secret:dms-source-AbCdEf"
        secrets_manager_access_role_arn = "arn:aws:iam::123456789012:role/dms-secrets-access"
        ssl_mode                        = "require"
      }
    }

    enabled = false
  }
}
