#!/usr/bin/env python3
"""Generate native OpenTofu offline tests (<module>/tests/offline.tftest.hcl).

For every module directory (contains main.tf) the script emits a tftest file
that mocks every required provider and plans the module twice:

  * run "plan_enabled"  - variables copied verbatim from test/test.tfvars
  * run "plan_disabled" - same variables plus enabled = false
                          (omitted for modules without an `enabled` variable,
                          i.e. the pass-through wrappers)

Mock providers return random strings for computed attributes, which trips
provider-side format validation (ARNs, JSON policies, ...). Per-module
mock_resource/mock_data overrides live in scripts/offline-test-mocks/
(<module path, "/" replaced by "__">.hcl) and are injected into the
mock_provider "aws" block. A small set of universally consumed mock_data
defaults (caller_identity / region / partition / iam_policy_document) is
always emitted.

Usage:
  scripts/generate-offline-tests.py                 # (re)generate all modules
  scripts/generate-offline-tests.py sns vpc         # subset
  scripts/generate-offline-tests.py --test          # generate + tofu test
  scripts/generate-offline-tests.py --test --jobs 8 # parallel test run
  scripts/generate-offline-tests.py --test --fix    # also iterate failures:
        parse format-validation errors, derive the mocked resource/data
        attribute that produced the invalid random value, append a sensible
        fake to the module's override file, regenerate and re-run (fixed
        point, max 10 iterations per module)

Hand-maintained negative tests: run blocks whose name starts with "invalid_"
(one per former test/fixtures/invalid-*.tfvars case, asserting a variable
validation fires via expect_failures) are written by hand directly in the
module's tests/offline.tftest.hcl. On regeneration the script extracts every
existing `run "invalid_*"` block - together with its directly attached
leading comment lines - and re-appends it verbatim after the generated runs,
so regeneration never loses them. Everything else in the file is owned by the
generator and overwritten.

The script is idempotent: regenerating produces identical files unless the
fixtures, providers or mock overrides changed.
"""

import argparse
import concurrent.futures
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MOCKS_DIR = os.path.join(ROOT, "scripts", "offline-test-mocks")
PLUGIN_CACHE = os.path.join(ROOT, ".terraform-plugin-cache")

# Providers that get a mock_provider block when required by the module.
# (`local` is intentionally absent: it is offline-safe and some modules read
# real fixture files through it at plan time.)
MOCKED_PROVIDERS = (
    "aws",
    "tls",
    "random",
    "cloudinit",
    "null",
    "docker",
    "kubernetes",
    "time",
    "external",
)

EMPTY_POLICY_JSON = '{\\"Version\\":\\"2012-10-17\\",\\"Statement\\":[{\\"Effect\\":\\"Allow\\",\\"Action\\":\\"*\\",\\"Resource\\":\\"*\\"}]}'

# mock_data defaults emitted in every aws mock block: these data sources are
# consumed across the repo and their computed attributes feed validated
# arguments (account ids, region names, partition DNS suffixes, policy JSON).
# Per-module overrides are merged on top (override file wins).
AWS_DEFAULT_MOCK_DATA = {
    ("mock_data", "aws_caller_identity"): {
        "account_id": '"123456789012"',
        "arn": '"arn:aws:iam::123456789012:root"',
        "user_id": '"AIDAMOCK"',
    },
    ("mock_data", "aws_region"): {
        "name": '"us-east-1"',
        "region": '"us-east-1"',
    },
    ("mock_data", "aws_partition"): {
        "partition": '"aws"',
        "dns_suffix": '"amazonaws.com"',
        "id": '"aws"',
    },
    ("mock_data", "aws_iam_policy_document"): {
        "json": '"%s"' % EMPTY_POLICY_JSON,
        "minified_json": '"%s"' % EMPTY_POLICY_JSON,
    },
}

HEADER = """\
# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/{override}.
# Regenerate with: python3 scripts/generate-offline-tests.py {module}
"""


def find_modules():
    mods = []
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [
            d
            for d in dirnames
            if d not in (".git", ".terraform", "examples", "fixtures")
        ]
        if "main.tf" in filenames:
            mods.append(os.path.relpath(dirpath, ROOT))
    return sorted(mods)


def required_providers(module_dir):
    """Provider local names declared in providers.tf required_providers."""
    path = os.path.join(ROOT, module_dir, "providers.tf")
    if not os.path.isfile(path):
        return ["aws"]
    with open(path) as f:
        text = f.read()
    names = re.findall(r"^\s+([a-z0-9_]+)\s*=\s*\{", text, re.M)
    return [n for n in names if n in MOCKED_PROVIDERS]


def has_enabled_variable(module_dir):
    for fn in os.listdir(os.path.join(ROOT, module_dir)):
        if fn.endswith(".tf"):
            with open(os.path.join(ROOT, module_dir, fn)) as f:
                if re.search(r'^variable\s+"enabled"', f.read(), re.M):
                    return True
    return False


def override_name(module_dir):
    return module_dir.replace("/", "__") + ".hcl"


def load_overrides(module_dir):
    path = os.path.join(MOCKS_DIR, override_name(module_dir))
    if os.path.isfile(path):
        with open(path) as f:
            return f.read().rstrip("\n")
    return ""


def tfvars_body(module_dir, strip_enabled=False):
    """test/test.tfvars content, indented for use inside a variables block."""
    path = os.path.join(ROOT, module_dir, "test", "test.tfvars")
    if not os.path.isfile(path):
        return None
    with open(path) as f:
        lines = f.read().rstrip("\n").split("\n")
    if strip_enabled:
        lines = [l for l in lines if not re.match(r"^enabled\s*=", l)]
    out = []
    for line in lines:
        out.append(("    " + line).rstrip() if line.strip() else "")
    return "\n".join(out)


def render(module_dir):
    providers = required_providers(module_dir) or ["aws"]
    enabled_var = has_enabled_variable(module_dir)
    variables = tfvars_body(module_dir)

    mocks = {k: dict(v) for k, v in AWS_DEFAULT_MOCK_DATA.items()}
    for key, attrs in parse_overrides(load_overrides(module_dir)).items():
        mocks.setdefault(key, {}).update(attrs)

    parts = [
        HEADER.format(override=override_name(module_dir), module=module_dir)
    ]
    for p in providers:
        if p == "aws":
            block = (
                'mock_provider "aws" {\n'
                + indent(render_overrides(mocks).rstrip("\n"), 2)
                + "\n}\n"
            )
            parts.append(block)
        else:
            parts.append('mock_provider "%s" {}\n' % p)

    if variables is None:
        # Wrapper modules: no fixture, every variable has a default. Plan with
        # minimal pass-through items to exercise the wiring offline.
        parts.append(
            "run \"plan_enabled\" {\n"
            "  command = plan\n\n"
            "  variables {\n"
            "    defaults = {}\n"
            "    items    = {}\n"
            "  }\n"
            "}\n"
        )
    else:
        parts.append(
            "run \"plan_enabled\" {\n"
            "  command = plan\n\n"
            "  variables {\n" + variables + "\n  }\n}\n"
        )
        if enabled_var:
            disabled_vars = tfvars_body(module_dir, strip_enabled=True)
            parts.append(
                "run \"plan_disabled\" {\n"
                "  command = plan\n\n"
                "  variables {\n" + disabled_vars + "\n\n"
                "    enabled = false\n"
                "  }\n}\n"
            )

    return "\n".join(parts)


def indent(text, n):
    pad = " " * n
    return "\n".join(pad + l if l.strip() else "" for l in text.split("\n"))


# Hand-maintained negative-test runs (ported from the old Terratest
# invalid-*.tfvars fixtures) live in the generated file but are preserved
# verbatim across regenerations - see the module docstring.
INVALID_RUN_RE = re.compile(r'^run\s+"invalid_[A-Za-z0-9_]+"\s*\{')


def extract_invalid_runs(path):
    """Return the hand-maintained `run "invalid_*"` blocks from an existing
    tftest file, each with its directly attached leading comment lines."""
    if not os.path.isfile(path):
        return []
    with open(path) as f:
        lines = f.read().split("\n")
    blocks, i = [], 0
    while i < len(lines):
        if not INVALID_RUN_RE.match(lines[i]):
            i += 1
            continue
        start = i
        while start > 0 and lines[start - 1].lstrip().startswith("#"):
            start -= 1
        depth, j = 0, i
        while j < len(lines):
            depth += lines[j].count("{") - lines[j].count("}")
            j += 1
            if depth <= 0:
                break
        blocks.append("\n".join(lines[start:j]).rstrip("\n"))
        i = j
    return blocks


def generate(module_dir):
    tests_dir = os.path.join(ROOT, module_dir, "tests")
    os.makedirs(tests_dir, exist_ok=True)
    path = os.path.join(tests_dir, "offline.tftest.hcl")
    invalid_runs = extract_invalid_runs(path)
    content = render(module_dir)
    if invalid_runs:
        content = (
            content.rstrip("\n") + "\n\n" + "\n\n".join(invalid_runs) + "\n"
        )
    with open(path, "w") as f:
        f.write(content)
    subprocess.run(
        ["tofu", "fmt", path], check=False, capture_output=True, cwd=ROOT
    )
    return path


# ---------------------------------------------------------------------------
# Auto-fix: derive mock defaults from plan-time format-validation errors.
# ---------------------------------------------------------------------------

ANSI_RE = re.compile(r"\x1b\[[0-9;]*m")
# data.aws_foo.bar.attr / aws_foo.bar[0].attr inside an error snippet line
REF_RE = re.compile(
    r"\b(data\.)?(aws_[a-z0-9_]+)\.[A-Za-z0-9_-]+(?:\[[^\]]*\])?\.([a-z0-9_]+)\b"
)
SNIPPET_RE = re.compile(r"^\s*\d+:\s")

ARN_SERVICE_OVERRIDES = {
    "db": "rds",
    "rds_cluster": "rds",
    "lb": "elasticloadbalancing",
    "alb": "elasticloadbalancing",
    "msk": "kafka",
    "mq": "mq",
    "sfn": "states",
    "cloudwatch": "logs",
}


# Resources whose `id` (or other attrs) must match a provider-validated
# format that the generic heuristics below cannot guess.
SPECIAL_VALUES = {
    ("aws_launch_template", "id"): "lt-1234567890abcdef0",
    ("aws_cognito_user_pool", "id"): "us-east-1_Mock12345",
    ("aws_ram_resource_share", "id"):
        "arn:aws:ram:us-east-1:123456789012:resource-share/mock",
    ("aws_ram_resource_share", "arn"):
        "arn:aws:ram:us-east-1:123456789012:resource-share/mock",
    ("aws_globalaccelerator_listener", "id"):
        "arn:aws:globalaccelerator::123456789012:accelerator/mock/listener/mock",
    ("aws_globalaccelerator_accelerator", "id"):
        "arn:aws:globalaccelerator::123456789012:accelerator/mock",
    ("aws_fsx_ontap_storage_virtual_machine", "id"): "svm-0123456789abcdef0",
    ("aws_appconfig_application", "id"): "a1b2c3d",
    ("aws_appconfig_environment", "environment_id"): "e1f2g3d",
    ("aws_appconfig_deployment_strategy", "id"): "d1e2f3c",
}


def guess_value(rtype, attr):
    """Sensible fake for a mocked computed attribute that failed validation."""
    if (rtype, attr) in SPECIAL_VALUES:
        return SPECIAL_VALUES[(rtype, attr)]
    if rtype.startswith("aws_fsx_") and attr == "id":
        return "fs-0123456789abcdef0"
    service = rtype.split("_", 2)[1] if "_" in rtype else rtype
    service = ARN_SERVICE_OVERRIDES.get(service, service)
    if attr == "arn" or attr.endswith("_arn"):
        if rtype.startswith("aws_iam_role"):
            return "arn:aws:iam::123456789012:role/mock"
        if rtype.startswith("aws_iam_"):
            return "arn:aws:iam::123456789012:policy/mock"
        if rtype.startswith("aws_s3_"):
            return "arn:aws:s3:::mock-bucket"
        if rtype == "aws_lambda_function":
            return "arn:aws:lambda:us-east-1:123456789012:function:mock"
        return "arn:aws:%s:us-east-1:123456789012:mock" % service
    if attr == "id" and rtype == "aws_vpc" or attr.endswith("vpc_id"):
        return "vpc-12345678"
    if attr == "id" and rtype == "aws_subnet" or attr.endswith("subnet_id"):
        return "subnet-12345678"
    if rtype == "aws_security_group" and attr == "id":
        return "sg-12345678"
    if attr.endswith("zone_id"):
        return "Z123456789012345678ABC"
    if rtype == "aws_sqs_queue" and attr in ("url", "id"):
        return "https://sqs.us-east-1.amazonaws.com/123456789012/mock"
    if "url" in attr or "endpoint" in attr:
        return "https://mock.example.com"
    if "cidr" in attr:
        return "10.0.0.0/16"
    if attr in ("json", "policy") or attr.endswith("_policy"):
        return EMPTY_POLICY_JSON.replace("\\\"", "\"")
    if "email" in attr:
        return "mock@example.com"
    if "kms_key" in attr or attr == "key_id":
        return "00000000-0000-0000-0000-000000000000"
    if "account_id" in attr:
        return "123456789012"
    return "mock-" + attr.replace("_", "-")


OVERRIDE_HEAD_RE = re.compile(r'^(mock_resource|mock_data)\s+"([a-z0-9_]+)"')
OVERRIDE_ATTR_RE = re.compile(r"^\s*([a-z0-9_]+)\s*=\s*(.+?)\s*$")


def parse_overrides(text):
    """Parse an override file into {(kind, rtype): {attr: raw_value}}.

    Line-based on the canonical render_overrides() format, so attribute
    values may safely contain braces (JSON policies, lists, objects).
    """
    out = {}
    attrs = None
    for line in text.split("\n"):
        head = OVERRIDE_HEAD_RE.match(line)
        if head:
            attrs = out.setdefault((head.group(1), head.group(2)), {})
            continue
        if attrs is None or line.strip() in ("", "defaults = {", "}", "{"):
            continue
        m = OVERRIDE_ATTR_RE.match(line)
        if m and m.group(1) != "defaults":
            attrs[m.group(1)] = m.group(2)
    return out


def render_overrides(data):
    blocks = []
    for (kind, rtype), attrs in sorted(data.items()):
        lines = ["%s \"%s\" {" % (kind, rtype), "  defaults = {"]
        for attr, value in sorted(attrs.items()):
            lines.append("    %s = %s" % (attr, value))
        lines += ["  }", "}"]
        blocks.append("\n".join(lines))
    return "\n\n".join(blocks) + "\n"


def hcl_quote(value):
    return '"%s"' % value.replace("\\", "\\\\").replace('"', '\\"')


# `Error: "logging_configuration.0.log_group_arn" (Xyz) is an invalid ...`
# `Error: "launch_template.0.id" must begin with 'lt-' ...`
ERROR_ATTR_RE = re.compile(r'^Error: "([a-z0-9_.]+)"')
# plugin-framework diagnostics name the attribute on a `Path:` detail line
PATH_RE = re.compile(r"^Path: ([a-z0-9_.\[\]]+)$")
# tofu rejects overrides of unknown or non-computed fields - undo those
BAD_FIELD_RE = re.compile(
    r"^Error: (?:Invalid mock/override field|Non-computed field) `([a-z0-9_]+)`"
)
WITH_RE = re.compile(r"^with (data\.)?([a-z0-9_]+)\.")


LOCAL_REF_RE = re.compile(r"\blocal\.([a-z0-9_]+)\b")


def refs_from_source(module_dir, attr_path, _depth=0, _seen=None):
    """Find `<attr> = <expr>` assignments in the module source.

    Fallback for diagnostics that point at a nested attribute: the snippet
    shows only the resource declaration line, so look the assignment up in
    the module's .tf files instead. Chases `local.*` references (locals are
    `name = expr` too) up to a small depth.
    """
    if _seen is None:
        _seen = set()
    leaf = re.sub(r"\[[^\]]*\]", "", attr_path).split(".")[-1]
    if leaf in _seen or _depth > 4:
        return []
    _seen.add(leaf)
    assign = re.compile(r"(?:^|[\s{(,])%s\s*=\s*(.+)$" % re.escape(leaf))
    found, locals_found = [], set()
    mod_path = os.path.join(ROOT, module_dir)
    for fn in sorted(os.listdir(mod_path)):
        if not fn.endswith(".tf"):
            continue
        with open(os.path.join(mod_path, fn)) as f:
            balance = 0
            for line in f:
                if balance > 0:  # continuation of a multi-line expression
                    rhs = line
                else:
                    m = assign.search(line)
                    if not m:
                        continue
                    rhs = m.group(1)
                found.extend(REF_RE.findall(rhs))
                locals_found.update(LOCAL_REF_RE.findall(rhs))
                balance += sum(rhs.count(c) for c in "([") - sum(
                    rhs.count(c) for c in ")]"
                )
                balance = max(balance, 0)
    for name in sorted(locals_found):
        found.extend(refs_from_source(module_dir, name, _depth + 1, _seen))
    return found


def derive_fixes(module_dir, output):
    """Derive override changes from tofu test diagnostics.

    Returns (additions, removals): additions are (kind, rtype, attr, value)
    for mocked refs whose generated value failed format validation; removals
    are (rtype, attr) override entries tofu itself rejected (unknown or
    non-computed field).
    """
    clean = ANSI_RE.sub("", output)
    additions, removals = [], []
    in_error = False
    error_attr = None
    bad_field = None
    for line in clean.split("\n"):
        stripped = line.strip().lstrip("│").strip()
        if stripped.startswith("Error:"):
            in_error = True
            m = ERROR_ATTR_RE.match(stripped)
            error_attr = m.group(1) if m else None
            m = BAD_FIELD_RE.match(stripped)
            bad_field = m.group(1) if m else None
            continue
        if not in_error:
            continue
        m = PATH_RE.match(stripped)
        if m:
            error_attr = m.group(1)
            for is_data, rtype, attr in refs_from_source(
                module_dir, error_attr
            ):
                kind = "mock_data" if is_data else "mock_resource"
                additions.append(
                    (kind, rtype, attr, hcl_quote(guess_value(rtype, attr)))
                )
            continue
        m = WITH_RE.match(stripped)
        if m and bad_field:
            removals.append((m.group(2), bad_field))
            bad_field = None
            continue
        if not SNIPPET_RE.match(stripped):
            continue
        refs = REF_RE.findall(stripped)
        if not refs and error_attr:
            refs = refs_from_source(module_dir, error_attr)
        for is_data, rtype, attr in refs:
            kind = "mock_data" if is_data else "mock_resource"
            additions.append(
                (kind, rtype, attr, hcl_quote(guess_value(rtype, attr)))
            )
    return additions, removals


def autofix(module_dir, output, deny):
    """Apply derived mock-default changes to the module override file.

    `deny` is a per-fix-session set of (rtype, attr) pairs that tofu has
    rejected as overrides - removed entries are added to it so the loop
    cannot oscillate between adding and removing the same field.

    Returns True when the override file changed (i.e. a re-run is worth it).
    """
    path = os.path.join(MOCKS_DIR, override_name(module_dir))
    existing = ""
    if os.path.isfile(path):
        with open(path) as f:
            existing = f.read()
    data = parse_overrides(existing)
    changed = False
    additions, removals = derive_fixes(module_dir, output)
    for rtype, attr in removals:
        deny.add((rtype, attr))
        for key in list(data):
            if key[1] == rtype and attr in data[key]:
                del data[key][attr]
                if not data[key]:
                    del data[key]
                changed = True
    for kind, rtype, attr, value in additions:
        if (rtype, attr) in deny:
            continue
        if attr in AWS_DEFAULT_MOCK_DATA.get((kind, rtype), {}):
            continue  # never clobber the always-on defaults
        attrs = data.setdefault((kind, rtype), {})
        if attr not in attrs:
            attrs[attr] = value
            changed = True
    if changed:
        os.makedirs(MOCKS_DIR, exist_ok=True)
        with open(path, "w") as f:
            f.write(render_overrides(data))
    return changed


def fix_module(module_dir, max_iters=10):
    mod, ok, output = run_test(module_dir)
    iters = 0
    deny = set()
    while not ok and iters < max_iters:
        if not autofix(module_dir, output, deny):
            break  # nothing derivable; needs a human
        generate(module_dir)
        mod, ok, output = run_test(module_dir)
        iters += 1
    return mod, ok, output


def run_test(module_dir):
    env = dict(os.environ, TF_PLUGIN_CACHE_DIR=PLUGIN_CACHE)
    cwd = os.path.join(ROOT, module_dir)
    if not os.path.isdir(os.path.join(cwd, ".terraform", "providers")):
        init = subprocess.run(
            ["tofu", "init", "-backend=false", "-input=false"],
            cwd=cwd, env=env, capture_output=True, text=True,
        )
        if init.returncode != 0:
            return module_dir, False, "init failed:\n" + init.stderr
    res = subprocess.run(
        ["tofu", "test"], cwd=cwd, env=env, capture_output=True, text=True
    )
    return module_dir, res.returncode == 0, res.stdout + res.stderr


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("modules", nargs="*", help="module dirs (default: all)")
    ap.add_argument("--test", action="store_true", help="run tofu test")
    ap.add_argument("--fix", action="store_true",
                    help="iterate failures, appending derived mock defaults")
    ap.add_argument("--no-generate", action="store_true")
    ap.add_argument("--jobs", type=int, default=6)
    args = ap.parse_args()

    modules = args.modules or find_modules()
    modules = [m.rstrip("/") for m in modules]

    if not args.no_generate:
        for m in modules:
            generate(m)
        print("generated %d test files" % len(modules))

    if not args.test:
        return 0

    failures = {}
    runner = fix_module if args.fix else run_test
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.jobs) as ex:
        for mod, ok, output in ex.map(runner, modules):
            print("%s %s" % ("PASS" if ok else "FAIL", mod), flush=True)
            if not ok:
                failures[mod] = output

    if failures:
        print("\n%d module(s) failed:" % len(failures))
        for mod in sorted(failures):
            print("\n===== %s =====" % mod)
            print(failures[mod])
        return 1
    print("\nall %d modules passed" % len(modules))
    return 0


if __name__ == "__main__":
    sys.exit(main())
