# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/xray.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py xray

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }
}

run "plan_enabled" {
  command = plan

  variables {
    enabled = true

    sampling_rules = {
      terratest-rule = {
        priority       = 100
        reservoir_size = 1
        fixed_rate     = 0.05
        service_name   = "terratest-service"
      }
    }

    groups = {
      terratest-group = {
        filter_expression = "service(\"terratest-service\")"
        insights_configuration = {
          insights_enabled      = true
          notifications_enabled = false
        }
      }
    }
  }
}

run "plan_disabled" {
  command = plan

  variables {

    sampling_rules = {
      terratest-rule = {
        priority       = 100
        reservoir_size = 1
        fixed_rate     = 0.05
        service_name   = "terratest-service"
      }
    }

    groups = {
      terratest-group = {
        filter_expression = "service(\"terratest-service\")"
        insights_configuration = {
          insights_enabled      = true
          notifications_enabled = false
        }
      }
    }

    enabled = false
  }
}
