# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/batch.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py batch

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }

  mock_resource "aws_batch_compute_environment" {
    defaults = {
      arn = "arn:aws:batch:us-east-1:123456789012:mock"
    }
  }

  mock_resource "aws_iam_role" {
    defaults = {
      arn = "arn:aws:iam::123456789012:role/mock"
    }
  }
}

run "plan_enabled" {
  command = plan

  variables {
    name   = "terratest-plan"
    vpc_id = "vpc-0123456789abcdef0"

    compute_resources = {
      type      = "FARGATE"
      max_vcpus = 4
      subnets   = ["subnet-12345678"]
    }

    job_queues = {
      default = {
        name     = "terratest-plan-default"
        priority = 1
      }
    }

    job_definitions = {
      hello = {
        name                 = "terratest-plan-hello"
        container_properties = "{\"image\":\"public.ecr.aws/amazonlinux/amazonlinux:latest\",\"command\":[\"echo\",\"hello\"],\"resourceRequirements\":[{\"type\":\"VCPU\",\"value\":\"0.25\"},{\"type\":\"MEMORY\",\"value\":\"512\"}]}"
      }
    }
  }
}

run "plan_disabled" {
  command = plan

  variables {
    name   = "terratest-plan"
    vpc_id = "vpc-0123456789abcdef0"

    compute_resources = {
      type      = "FARGATE"
      max_vcpus = 4
      subnets   = ["subnet-12345678"]
    }

    job_queues = {
      default = {
        name     = "terratest-plan-default"
        priority = 1
      }
    }

    job_definitions = {
      hello = {
        name                 = "terratest-plan-hello"
        container_properties = "{\"image\":\"public.ecr.aws/amazonlinux/amazonlinux:latest\",\"command\":[\"echo\",\"hello\"],\"resourceRequirements\":[{\"type\":\"VCPU\",\"value\":\"0.25\"},{\"type\":\"MEMORY\",\"value\":\"512\"}]}"
      }
    }

    enabled = false
  }
}
