# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/route53__zone.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py route53/zone

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }

  mock_resource "aws_cloudwatch_log_group" {
    defaults = {
      arn = "arn:aws:logs:us-east-1:123456789012:mock"
    }
  }
}

run "plan_enabled" {
  command = plan

  variables {
    zones = {
      "test.example.com" = {}

      "signed.example.com" = {
        dnssec = {
          kms_key_arn = "arn:aws:kms:us-east-1:111111111111:key/00000000-0000-0000-0000-000000000000"
        }
        query_logging = {
          log_group_retention_in_days = 90
        }
      }
    }

    create_query_log_resource_policy = true
  }
}

run "plan_disabled" {
  command = plan

  variables {
    zones = {
      "test.example.com" = {}

      "signed.example.com" = {
        dnssec = {
          kms_key_arn = "arn:aws:kms:us-east-1:111111111111:key/00000000-0000-0000-0000-000000000000"
        }
        query_logging = {
          log_group_retention_in_days = 90
        }
      }
    }

    create_query_log_resource_policy = true

    enabled = false
  }
}
