# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/global-accelerator.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py global-accelerator

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }

  mock_resource "aws_globalaccelerator_listener" {
    defaults = {
      id = "arn:aws:globalaccelerator::123456789012:accelerator/mock/listener/mock"
    }
  }
}

run "plan_enabled" {
  command = plan

  variables {
    name = "terratest-plan"

    listeners = {
      http = {
        protocol = "TCP"
        port_ranges = [
          { from_port = 80, to_port = 80 },
        ]
      }
    }

    endpoint_groups = {
      http = {
        listener_key          = "http"
        endpoint_group_region = "us-east-1"
        endpoint_configurations = [
          {
            endpoint_id = "arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/app/test/0123456789abcdef"
            weight      = 100
          },
        ]
      }
    }
  }
}

run "plan_disabled" {
  command = plan

  variables {
    name = "terratest-plan"

    listeners = {
      http = {
        protocol = "TCP"
        port_ranges = [
          { from_port = 80, to_port = 80 },
        ]
      }
    }

    endpoint_groups = {
      http = {
        listener_key          = "http"
        endpoint_group_region = "us-east-1"
        endpoint_configurations = [
          {
            endpoint_id = "arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/app/test/0123456789abcdef"
            weight      = 100
          },
        ]
      }
    }

    enabled = false
  }
}
