# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/s3.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py s3

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }
}

run "plan_enabled" {
  command = plan

  variables {
    name = "terratest-plan-bucket"
  }
}

run "plan_disabled" {
  command = plan

  variables {
    name = "terratest-plan-bucket"

    enabled = false
  }
}

# Hand-maintained negative test (preserved verbatim by generate-offline-tests.py).
# Must fail: attach_deny_incorrect_kms_key_sse = true requires allowed_kms_key_arn.
run "invalid_kms_policy_no_key" {
  command = plan

  variables {
    name                              = "terratest-plan-bucket"
    attach_deny_incorrect_kms_key_sse = true
    # allowed_kms_key_arn intentionally omitted (defaults to null)
  }

  expect_failures = [
    var.attach_deny_incorrect_kms_key_sse,
  ]
}
