# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/eks.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py eks

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }

  mock_resource "aws_eks_cluster" {
    defaults = {
      certificate_authority = [{ data = "bW9jay1jZXJ0aWZpY2F0ZS1kYXRh" }]
      identity              = [{ oidc = [{ issuer = "https://oidc.eks.us-east-1.amazonaws.com/id/MOCK1234567890" }] }]
    }
  }

  mock_resource "aws_iam_policy" {
    defaults = {
      arn = "arn:aws:iam::123456789012:policy/mock"
    }
  }

  mock_resource "aws_iam_role" {
    defaults = {
      arn = "arn:aws:iam::123456789012:role/mock"
    }
  }
}

mock_provider "tls" {}

mock_provider "time" {}

run "plan_enabled" {
  command = plan

  variables {
    name            = "terratest-plan"
    cluster_version = "1.31"
    vpc_id          = "vpc-12345678"
    subnet_ids      = ["subnet-12345678", "subnet-87654321"]
  }
}

run "plan_disabled" {
  command = plan

  variables {
    name            = "terratest-plan"
    cluster_version = "1.31"
    vpc_id          = "vpc-12345678"
    subnet_ids      = ["subnet-12345678", "subnet-87654321"]

    enabled = false
  }
}
