# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/cloudwatch__modules__synthetics.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py cloudwatch/modules/synthetics

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }

  mock_resource "aws_iam_role" {
    defaults = {
      arn = "arn:aws:iam::123456789012:role/mock"
    }
  }
}

run "plan_enabled" {
  command = plan

  variables {
    name = "terratest-plan"

    canaries = {
      # Exercises the default-fallback paths: no artifact_s3_location,
      # create_alarm unset (falls back to create_canary_alarms),
      # all alarm_* attributes unset (fall back to module defaults).
      defaults = {
        name                = "terratest-defaults"
        handler             = "index.handler"
        runtime_version     = "syn-nodejs-puppeteer-9.1"
        schedule_expression = "rate(5 minutes)"
        zip_file            = "test/canary.zip"
      }

      # Exercises explicit overrides.
      overrides = {
        name                     = "terratest-overrides"
        handler                  = "index.handler"
        runtime_version          = "syn-nodejs-puppeteer-9.1"
        schedule_expression      = "rate(10 minutes)"
        zip_file                 = "test/canary.zip"
        artifact_s3_location     = "s3://my-existing-bucket/custom-prefix"
        success_retention_period = 7
        failure_retention_period = 14
        create_alarm             = true
        alarm_name               = "terratest-overrides-custom-alarm"
        alarm_evaluation_periods = 2
        alarm_period             = 600
        alarm_threshold          = 90
        alarm_actions            = ["arn:aws:sns:us-east-1:123456789012:alerts"]
        run_config = {
          timeout_in_seconds = 120
          memory_in_mb       = 1024
        }
      }
    }

    canary_groups = {
      terratest-group = {
        canary_keys = ["defaults", "overrides"]
      }
    }
  }
}

run "plan_disabled" {
  command = plan

  variables {
    name = "terratest-plan"

    canaries = {
      # Exercises the default-fallback paths: no artifact_s3_location,
      # create_alarm unset (falls back to create_canary_alarms),
      # all alarm_* attributes unset (fall back to module defaults).
      defaults = {
        name                = "terratest-defaults"
        handler             = "index.handler"
        runtime_version     = "syn-nodejs-puppeteer-9.1"
        schedule_expression = "rate(5 minutes)"
        zip_file            = "test/canary.zip"
      }

      # Exercises explicit overrides.
      overrides = {
        name                     = "terratest-overrides"
        handler                  = "index.handler"
        runtime_version          = "syn-nodejs-puppeteer-9.1"
        schedule_expression      = "rate(10 minutes)"
        zip_file                 = "test/canary.zip"
        artifact_s3_location     = "s3://my-existing-bucket/custom-prefix"
        success_retention_period = 7
        failure_retention_period = 14
        create_alarm             = true
        alarm_name               = "terratest-overrides-custom-alarm"
        alarm_evaluation_periods = 2
        alarm_period             = 600
        alarm_threshold          = 90
        alarm_actions            = ["arn:aws:sns:us-east-1:123456789012:alerts"]
        run_config = {
          timeout_in_seconds = 120
          memory_in_mb       = 1024
        }
      }
    }

    canary_groups = {
      terratest-group = {
        canary_keys = ["defaults", "overrides"]
      }
    }

    enabled = false
  }
}
