# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/cloudfront.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py cloudfront

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }
}

run "plan_enabled" {
  command = plan

  variables {
    origin = {
      s3 = {
        domain_name = "terratest-bucket.s3.amazonaws.com"
        origin_id   = "s3-origin"
      }
    }
    default_cache_behavior = {
      target_origin_id       = "s3-origin"
      viewer_protocol_policy = "redirect-to-https"
      allowed_methods        = ["GET", "HEAD"]
      cached_methods         = ["GET", "HEAD"]
      # AWS managed CachingOptimized policy
      cache_policy_id = "658327ea-f89d-4fab-a63d-7e88639e58f6"
    }
    ordered_cache_behavior = [
      {
        path_pattern           = "/static/*"
        target_origin_id       = "s3-origin"
        viewer_protocol_policy = "redirect-to-https"
        # AWS managed CachingOptimized policy
        cache_policy_id = "658327ea-f89d-4fab-a63d-7e88639e58f6"
      }
    ]
  }
}

run "plan_disabled" {
  command = plan

  variables {
    origin = {
      s3 = {
        domain_name = "terratest-bucket.s3.amazonaws.com"
        origin_id   = "s3-origin"
      }
    }
    default_cache_behavior = {
      target_origin_id       = "s3-origin"
      viewer_protocol_policy = "redirect-to-https"
      allowed_methods        = ["GET", "HEAD"]
      cached_methods         = ["GET", "HEAD"]
      # AWS managed CachingOptimized policy
      cache_policy_id = "658327ea-f89d-4fab-a63d-7e88639e58f6"
    }
    ordered_cache_behavior = [
      {
        path_pattern           = "/static/*"
        target_origin_id       = "s3-origin"
        viewer_protocol_policy = "redirect-to-https"
        # AWS managed CachingOptimized policy
        cache_policy_id = "658327ea-f89d-4fab-a63d-7e88639e58f6"
      }
    ]

    enabled = false
  }
}
