# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/lambda.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py lambda

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }

  mock_resource "aws_iam_policy" {
    defaults = {
      arn = "arn:aws:iam::123456789012:policy/mock"
    }
  }

  mock_resource "aws_iam_role" {
    defaults = {
      arn = "arn:aws:iam::123456789012:role/mock"
    }
  }
}

mock_provider "external" {}

mock_provider "null" {}

run "plan_enabled" {
  command = plan

  variables {
    name           = "terratest-plan"
    handler        = "index.handler"
    runtime        = "python3.12"
    package_type   = "Image"
    image_uri      = "123456789012.dkr.ecr.us-east-1.amazonaws.com/lambda-test:latest"
    create_package = false
    source_path    = null
  }
}

run "plan_disabled" {
  command = plan

  variables {
    name           = "terratest-plan"
    handler        = "index.handler"
    runtime        = "python3.12"
    package_type   = "Image"
    image_uri      = "123456789012.dkr.ecr.us-east-1.amazonaws.com/lambda-test:latest"
    create_package = false
    source_path    = null

    enabled = false
  }
}
