# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/opensearch.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py opensearch

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_iam_session_context" {
    defaults = {
      issuer_arn = "arn:aws:iam::123456789012:policy/mock"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }

  mock_resource "aws_cloudwatch_log_group" {
    defaults = {
      arn = "arn:aws:logs:us-east-1:123456789012:mock"
    }
  }
}

run "plan_enabled" {
  command = plan

  variables {
    name               = "terratest"
    opensearch_version = "OpenSearch_2.11"
    cluster_config = {
      instance_type          = "t3.small.search"
      instance_count         = 1
      zone_awareness_enabled = false
    }
  }
}

run "plan_disabled" {
  command = plan

  variables {
    name               = "terratest"
    opensearch_version = "OpenSearch_2.11"
    cluster_config = {
      instance_type          = "t3.small.search"
      instance_count         = 1
      zone_awareness_enabled = false
    }

    enabled = false
  }
}
