# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/cognito.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py cognito

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }

  mock_resource "aws_cognito_user_pool" {
    defaults = {
      id = "us-east-1_Mock12345"
    }
  }
}

run "plan_enabled" {
  command = plan

  variables {
    name   = "terratest-plan"
    domain = "terratest-plan"

    resource_servers = {
      orders-api = {
        identifier = "https://orders.terratest-plan.example.com"
        scopes = [
          {
            scope_name        = "read"
            scope_description = "Read access to the orders API"
          },
          {
            scope_name        = "write"
            scope_description = "Write access to the orders API"
          },
        ]
      }
    }

    user_groups = {
      admins = {
        description = "Administrators"
        precedence  = 1
      }
      readers = {
        description = "Read-only users"
        precedence  = 10
      }
    }
  }
}

run "plan_disabled" {
  command = plan

  variables {
    name   = "terratest-plan"
    domain = "terratest-plan"

    resource_servers = {
      orders-api = {
        identifier = "https://orders.terratest-plan.example.com"
        scopes = [
          {
            scope_name        = "read"
            scope_description = "Read access to the orders API"
          },
          {
            scope_name        = "write"
            scope_description = "Write access to the orders API"
          },
        ]
      }
    }

    user_groups = {
      admins = {
        description = "Administrators"
        precedence  = 1
      }
      readers = {
        description = "Read-only users"
        precedence  = 10
      }
    }

    enabled = false
  }
}
