# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/security-hub.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py security-hub

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }
}

run "plan_enabled" {
  command = plan

  variables {
    name = "terratest-plan"

    automation_rules = {
      suppress-sandbox-informational = {
        rule_order  = 1
        description = "Suppress informational findings from the sandbox account"
        criteria = {
          aws_account_id = [{ comparison = "EQUALS", value = "111111111111" }]
          severity_label = [{ comparison = "EQUALS", value = "INFORMATIONAL" }]
        }
        actions = {
          workflow_status = "SUPPRESSED"
          note_text       = "Auto-suppressed by automation rule"
        }
      }
    }

    insights = {
      critical-findings-by-resource = {
        group_by_attribute = "ResourceId"
        filters = {
          severity_label  = [{ comparison = "EQUALS", value = "CRITICAL" }]
          workflow_status = [{ comparison = "EQUALS", value = "NEW" }]
          record_state    = [{ comparison = "EQUALS", value = "ACTIVE" }]
        }
      }
    }
  }
}

run "plan_disabled" {
  command = plan

  variables {
    name = "terratest-plan"

    automation_rules = {
      suppress-sandbox-informational = {
        rule_order  = 1
        description = "Suppress informational findings from the sandbox account"
        criteria = {
          aws_account_id = [{ comparison = "EQUALS", value = "111111111111" }]
          severity_label = [{ comparison = "EQUALS", value = "INFORMATIONAL" }]
        }
        actions = {
          workflow_status = "SUPPRESSED"
          note_text       = "Auto-suppressed by automation rule"
        }
      }
    }

    insights = {
      critical-findings-by-resource = {
        group_by_attribute = "ResourceId"
        filters = {
          severity_label  = [{ comparison = "EQUALS", value = "CRITICAL" }]
          workflow_status = [{ comparison = "EQUALS", value = "NEW" }]
          record_state    = [{ comparison = "EQUALS", value = "ACTIVE" }]
        }
      }
    }

    enabled = false
  }
}
