# Generated by scripts/generate-offline-tests.py - do not edit by hand.
# Extra mock defaults live in scripts/offline-test-mocks/ec2.hcl.
# Regenerate with: python3 scripts/generate-offline-tests.py ec2

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "AIDAMOCK"
    }
  }

  mock_data "aws_iam_policy_document" {
    defaults = {
      json          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
      minified_json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
    }
  }

  mock_data "aws_partition" {
    defaults = {
      dns_suffix = "amazonaws.com"
      id         = "aws"
      partition  = "aws"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name   = "us-east-1"
      region = "us-east-1"
    }
  }
}

run "plan_enabled" {
  command = plan

  variables {
    name          = "terratest-plan"
    ami           = "ami-0c02fb55956c7d316"
    instance_type = "t3.micro"
    subnet_id     = "subnet-12345678"

    create_iam_instance_profile = true
    iam_role_name               = "terratest-plan"

    root_block_device = [
      {
        volume_size = 20
        volume_type = "gp3"
      }
    ]

    ebs_block_device = [
      {
        device_name = "/dev/sdf"
        volume_size = 10
        volume_type = "gp3"
      }
    ]
  }
}

run "plan_disabled" {
  command = plan

  variables {
    name          = "terratest-plan"
    ami           = "ami-0c02fb55956c7d316"
    instance_type = "t3.micro"
    subnet_id     = "subnet-12345678"

    create_iam_instance_profile = true
    iam_role_name               = "terratest-plan"

    root_block_device = [
      {
        volume_size = 20
        volume_type = "gp3"
      }
    ]

    ebs_block_device = [
      {
        device_name = "/dev/sdf"
        volume_size = 10
        volume_type = "gp3"
      }
    ]

    enabled = false
  }
}
